#!/bin/bash
gradle fatJarWebApp
gradle fatJarServer


java -jar webapp/build/libs/webapp-all-1.0.jar > logs/webapp.log 2>&1 &
webappPid=$!
echo "webappPid=$webappPid" > pids
java -jar server/build/libs/server-all-1.0.jar > logs/server.log 2>&1 &
serverPid=$!
echo "serverPid=$serverPid" >> pids
